#!/usr/bin/env python3

import sys
import os
import helpers
from analyzer import Analyzer
from termcolor import colored

if len(sys.argv) != 2:
    sys.exit("Usage: ./tweets screenname")
uname = sys.argv[1]
tweets = helpers.get_user_timeline(uname, 50)
positives = os.path.join(sys.path[0], "positive-words.txt")
negatives = os.path.join(sys.path[0], "negative-words.txt")
analyzer = Analyzer(positives, negatives)
for tweet in tweets:
    score = analyzer.analyze(tweet)
    output = "%d %s" % (score, tweet)
    if score > 0.0:
        print(colored(output, "green"))
    elif score < 0.0:
        print(colored(output, "red"))
    else:
        print(colored(output, "yellow"))
